import type { Metadata } from "next";
import localFont from "next/font/local";

import { PrimeReactProvider } from 'primereact/api';

import NavBar from "@/components/NavBar";
import MenuBar from "@/components/MenuBar";
import { UserStoreProvider } from "@/store/UserContext";

import "./globals.css";
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider>
          <NavBar />
          <MenuBar />
            <UserStoreProvider>
            {children}
          </UserStoreProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
